In [1]:
import pandas as pd

In [5]:
# Specify the path to your CSV file
csv_path = 'C:/Users/sedad/Documents/ForestFire/Data/effis_europe_2008_2022.csv'

# Read the CSV file using pandas
df = pd.read_csv(csv_path)

In [7]:
# Display the contents of the CSV file

,X,Y,id,initialdate,finaldate,area_ha,iso2,iso3,country,admlvl1,...,transitional_vegetation_percent,other_natural_percent,agriculture_percent,artificial_percent,other_percent,natura2k_percent,noneu,updated,area_code,eu_area
0,NaN,NaN,39205,2008/07/10 00:00:00,2008/07/10 00:00:00+00,79,ES,ESP,España,Sur,...,0.000000,0.000000,0.000000,0.0,0.0,100.0,0,2022/01/26 11:57:54.973,EU,EU
1,NaN,NaN,39987,2008/09/28 00:00:00,2008/09/28 00:00:00+00,176,PT,PRT,Portugal,Continente,...,55.617978,19.662921,0.000000,0.0,0.0,0.0,0,2022/01/26 11:57:54.973,EU,EU
2,NaN,NaN,39989,2008/09/30 00:00:00,2008/09/30 00:00:00+00,211,FR,FRA,France,Occitanie,...,0.000000,0.000000,13.942308,0.0,0.0,0.0,0,2022/01/26 11:57:54.973,EU,EU
3,NaN,NaN,39991,2008/10/05 00:00:00,2008/10/05 00:00:00+00,281,PT,PRT,Portugal,Continente,...,70.106762,19.572954,4.982206,0.0,0.0,0.0,0,2022/01/26 11:57:54.973,EU,EU
4,NaN,NaN,39993,2008/10/05 00:00:00,2008/10/05 00:00:00+00,100,PT,PRT,Portugal,Continente,...,100.000000,0.000000,0.000000,0.0,0.0,0.0,0,2022/01/26 11:57:54.973,EU,EU
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28001,NaN,NaN,198950,2022/03/19 11:19:00,2022/03/19 11:19:00+00,304,BA,BIH,Bosnia and Herzegovina,Repuplika Srpska,...,0.000000,16.339869,27.450980,0.0,0.0,0.0,1,2023/02/22 19:03:41.881,EU,EU_non
28002,NaN,NaN,192923,2022/03/15 11:42:00,2022/03/15 11:42:00+00,282,RO,ROU,România,Macroregiunea Unu,...,0.000000,0.000000,44.839858,0.0,0.0,100.0,0,2023/02/22 19:03:41.881,EU,EU
28003,NaN,NaN,193114,2022/03/15 00:16:00,2022/03/15 00:16:00+00,215,HU,HUN,Magyarország,Alföld és Észak,...,0.000000,0.000000,73.488372,0.0,0.0,0.0,0,2023/02/22 19:03:41.881,EU,EU
28004,NaN,NaN,183483,2022/03/15 11:42:00,2022/03/15 11:42:00+00,4594,BA,BIH,Bosnia and Herzegovina,Repuplika Srpska,...,5.907906,0.000000,1.498697,0.0,0.0,0.0,1,2023/02/22 19:03:41.881,EU,EU_non
28005,NaN,NaN,206710,2022/07/22 20:02:00,2022/07/22 20:02:00+00,290,RS,SRB,Serbia,Pomoravski,...,36.301370,45.890411,0.000000,0.0,0.0,0.0,1,2023/02/22 19:03:41.881,EU,EU_non